# Generated by Django 2.1.3 on 2019-08-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190823_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('Food', 'Where to eat'), ('Activities', 'What to do'), ('Accommodation', 'Where to stay')], default='Activities', max_length=30),
        ),
    ]
