# Generated by Django 2.1.3 on 2019-08-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[(1, 'Food'), (2, 'Activities'), (3, 'Accommodation')], default=2, max_length=30),
        ),
    ]
