# Generated by Django 2.1.3 on 2019-08-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190826_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('Food', 'Food'), ('Activities', 'Activities'), ('Accommodation', 'Accommodation')], default=2, max_length=30),
        ),
    ]
